### ISSUE TITLE
Pass tokens with Catalog API requests

### ISSUE THREAD

**Issue by marshallmcdonnell** [smart-spectral-matching/ssm-ui-catalog#2]
Refactor the frontend UI calls to the Catalog API so that it uses tokens for authN.

**Comment by marshallmcdonnell** [comment]
@SmithRWORNL has this working for the ssm-ui-ml calls to the ssm-service-catalog.
Link: https://github.com/smart-spectral-matching/ssm-ui-ml/blob/main/src/main/java/gov/ornl/ssm/ml/ui/views/TrainingView.java#L134-L137

We need to do same thing for this UI for calls to ssm-service-catalog

**Comment by marshallmcdonnell** [comment]
@gecage952 I believe this issue is closed with your work from PR https://github.com/smart-spectral-matching/ssm-ui-catalog/pull/5

Do you care to confirm?

If so, feel free to close this issue.

Thanks

**Comment by gecage952** [comment]
Yeah, I'll close this out now.
